name: Pipeline Automatizado de Extracción Retail

on:
  schedule:
    - cron: '0 7 * * *'
  workflow_dispatch:

permissions:
  contents: write

# AÑADIMOS ESTO PARA ELIMINAR EL AVISO DE NODE.JS Y ACTUALIZAR LOS SERVIDORES
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 1. Clonar el repositorio
      uses: actions/checkout@v4

    - name: 2. Configurar el entorno de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 3. Instalar dependencias del sistema
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: 4. Ejecutar el Extractor de Precios y Stock
      run: python extractor.py

    - name: 5. Guardar cambios en la Base de Datos de GitHub
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add retail_history.db
        git diff --quiet && git diff --staged --quiet || (git commit -m "Pipeline: Actualización diaria de precios e histórico transaccional" && git push)
